### ISSUE TITLE
Output in view

### ISSUE THREAD

**Issue by honsa** [thamtech/yii2-scheduler#4]
**-** ` return Html::tag('span', '', ['class' => $m->error == 0 ? 'text-success glyphicon glyphicon-ok-circle' : 'text-danger glyphicon glyphicon-remove-circle']);`

**+** `return Html::tag('span', $m->output, ['class' => $m->error == 0 ? 'text-success glyphicon glyphicon-ok-circle' : 'text-danger glyphicon glyphicon-remove-circle']);`

https://github.com/thamtech/yii2-scheduler/pull/2/commits/8d7bcc987b17f155b9b119950df12777cc9081fe

> I don't agree with the change in the Output in view commit and won't merge it in at this time. I don't believe the change is necessary, but if you'd like to create a separate issue for it, we can continue discussing it there.

https://github.com/thamtech/yii2-scheduler/pull/2#issuecomment-563016832

What should be there instead?

Your code generates an empty span with different class depending on errors in the runned task. 
So as user you see nothing if you are not reading the markup. 
If you want to keep it empty I would remove the whole column.

**Comment by honsa** [comment]
But anyway, you merged it already with the other pull request :)

**Comment by tyler-ham** [comment]
That is a good point. That column isn't supposed to be empty, but it currently relies on [Bootstrap glyphicons](https://getbootstrap.com/docs/3.4/components/#glyphicons) to indicate success or failure. We shouldn't assume glyphicons are available, though, since that leads to the column appearing empty as it does for you.

I prefer not to include the actual log output here. It could be a rather large amount of text to reasonably fit in the table cell, so my preference is to keep it only on the screen rendered by `view-log.php`.

Instead, I believe we should keep the empty span with the glyphicons, but append "Success"/"Failure" text. If a project has glyphicons available, the icons will be a nice visual associated with the text. Otherwise, the empty span will be ignored and the column will just display the text. The text itself could still carry they `text-success` or `text-danger` class for some additional visual distinction.

**Comment by honsa** [comment]
In my case, just admins have access to the view, and they are happy if they see an error or success message. 

Sure succeed/failed would do it.
